export const APPS = {
    ADD: 'ADD_APP',
    SET: 'SET_APP',
    SET_APPS: 'SET_APPS',
    CLOSE: 'CLOSE_APP'
};

export const CONTACTS = {
    ADD: 'ADD_CONTACT',
    REMOVE: 'REMOVE_CONTACT',
    UPDATE: 'UPDATE_CONTACT'
};

export const DIALOGS = {
    LOAD: 'LOAD_DIALOGS',
    ADD: 'ADD_DIALOG',
    ADD_MESSAGE: 'ADD_MESSAGE',
    READ: 'READ_DIALOG',
    RENAME: 'RENAME_DIALOG',
    REMOVE: 'REMOVE_DIALOG'
};

export const HOUSE = {
    CHANGE_STATE: 'CHANGE_STATE_HOUSE',
    SET_SELL_STATUS: 'SET_SELL_STATUS_HOUSE',
    SET_SELL_INFO: 'SET_SELL_INFO_HOUSE',
    SELL: 'SELL_HOUSE',
    BUY_IMPROVEMENT: 'BUY_IMPROVEMENT_HOUSE',
    BUY_IMPROVEMENT_ANS: 'BUY_IMPROVEMENT_HOUSE_ANS'
};

export const BIZ = {
    SET_SELL_STATUS: 'SET_SELL_STATUS_BUSINESS',
    SET_SELL_INFO: 'SET_SELL_INFO_BUSINESS',
    CREATE_ORDER: 'CREATE_ORDER_BUSINESS',
    CANCEL_ORDER: 'CANCEL_ORDER_BUSINESS',
    SET_ORDER_STATUS: 'SET_ORDER_STATUS_BUSINESS',
    TAKE_ORDER: 'TAKE_ORDER_BUSINESS',
    COMPLETE_ORDER: 'ORDER_COMPLETE_BUSINESS',
    UPDATE_PRODUCTS: 'UPDATE_PRODUCTS_BUSINESS',
    SELL: 'SELL_BUSINESS',
    BUY_IMPROVEMENT: 'BUY_IMPROVEMENT_BUSINESS',
    BUY_IMPROVEMENT_ANS: 'BUY_IMPROVEMENT_BUSINESS_ANS',
    UPDATE_CASHBOX: 'UPDATE_CASHBOX_BUSINESS',
    UPDATE_STATISTICS: 'UPDATE_STATISTICS_BUSINESS',
};

export const BANK_APP = {
    SHOW: 'SHOW_BANK_APP',
    TRANSFER: 'TRANSFER_BANK_APP',
    ASK_ANSWER: 'SET_ASK_ANSWER_BANK_APP',
    ANSWER: 'SET_ANSWER_BANK_APP',
    UPDATE: 'UPDATE_BANK',
    PAY_HOUSE: 'PAY_HOUSE_BANK_APP',
    PAY_BIZ: 'PAY_BIZ_BANK_APP',
    TAXES_HOUSE: 'TAXES_HOUSE_BANK_APP',
    TAXES_BIZ: 'TAXES_BIZ_BANK_APP'
};